name: React CI

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }} # Project ID from lachezar account
  SERVICE: react-app # Google Cloud Run service name
  REGION: europe-west4

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap_scan:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://react-app-xwjwz3lfdq-ez.a.run.app'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
