name: ZAP Scan CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap_scan:
    name: ZAP Scan
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://react-app-xwjwz3lfdq-ez.a.run.app'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
