name: React CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Lint
      run: npm run lint

      # Uncomment when I have tests
    #- name: Run Tests
    #  run: npm test

    - name: Build
      run: npm run build
