name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      working-directory: ./frontend
      run: npm install

    # Reintroduce Lint without failing the build
    - name: Lint (Non-Failing)
      working-directory: ./frontend
      run: npm run lint || echo "Lint errors detected, but proceeding with build."

    # Uncomment when you have tests
    #- name: Run Tests
    #  working-directory: ./frontend
    #  run: npm test

    - name: Build
      working-directory: ./frontend
      run: npm run build
      
  docker-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: luchoo
          password: dckr_pat_XhqG0UEN8_E0Eupyce8tyfI4nBE
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: luchoo/react-app:latest,luchoo/react-app:${{ github.sha }}
